language: ruby
rvm:
  - 2.1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libxml2-dev postgresql-server-dev-all

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c 'create database online_trader_test;' -U postgres
  - bundle exec rake db:automigrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./test.sh

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    recipients:
      - grantspeelman+travis@gmail.com
    on_success: change
    on_failure: change
