language: ruby
rvm:
  - 2.1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libxml2-dev

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c 'create database online_trader_test;' -U postgres
  - bundle exec rake db:automigrate

script:
  - ./test.sh

notifications:
  email:
    recipients:
      - grantspeelman+travis@gmail.com
    on_success: change
    on_failure: change
