development:
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  user: postgres
  database: online_trader_development

test:
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  user: postgres
  database: online_trader_test

production:
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL') %>
