development:
  url: jdbc:postgresql://<%= ENV['DB_HOST'] || 'localhost' %>/online_trader_development?user=postgres

test:
  url: jdbc:postgresql://<%= ENV['DB_HOST'] || 'localhost' %>/online_trader_test?user=postgres
