development:
  adapter: postgresql
  url: postgres://postgres@<%= ENV['DB_HOST'] || 'localhost' %>/online_trader_development

test:
  adapter: postgresql
  url: postgres://postgres@<%= ENV['DB_HOST'] || 'localhost' %>/online_trader_test
