development:
  host: localhost
  database: yugioh_online_trader_development

test:
  host: localhost
  database: yugioh_online_trader_test

# set these environment variables on your prod server
production:
  host: dbh70.mongolab.com
  port: 27707
  username: test
  password: test
  database: heroku_app2446995
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
